### ISSUE TITLE
Add "getting started" instructions to README

### ISSUE THREAD

**Issue by nicholastmosher** [Littlewil35/Website#3]
This project seems to take a little bit of setup work, it doesn't run out-of-the-box when I use `python3 app.py`. Some of the things I noticed need doing include:

* Installing dependencies from `requirements.txt`
* Choosing a `.sqlite` database file (yours is currently hardcoded in the code)
  * As an extra suggestion, I'd recommend making your database file choice via an environment variable so you don't need to edit your app's code to change your data

I'd recommend adding a Getting Started section to your README so that somebody who's never used flask or python could follow the instructions step by step until they have the project launched.

**Comment by nicholastmosher** [comment]
Note: In order to install SQLAlchemy, I used `pip3 install --user -r requirements.txt`

**Comment by nicholastmosher** [comment]
After installing dependencies and trying to run for the first time (using `python3 app.py`) I got the following error about not being able to open the DB file:

```
[2020-04-07 10:01:29,305] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
    return self._create_connection()
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/nick/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 481, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file
```

I already pointed the DB file address to a location on my computer, so that wasn't the problem. You may want to create an initialization script that sets up all of the necessary tables for a first run.
